import styles from './table-wcag.module.scss';

export const TableWcag = () => {
  return (
    <div className={styles.tableWrap}>
      <table>
        <thead>
          <tr>
            <th>No.</th>
            <th>達成基準</th>
            <th>適合レベル</th>
            <th>適用</th>
            <th>備考</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th>1.1.1</th>
            <td>非テキストコンテンツ</td>
            <td>A</td>
            <td>○</td>
            <td>適宜画像に代替えテキストを設定</td>
          </tr>
          <tr>
            <th>1.2.1</th>
            <td>音声だけ及び映像だけ（収録済み）</td>
            <td>A</td>
            <td>-</td>
            <td>該当コンテンツなし</td>
          </tr>
          <tr>
            <th>1.2.2</th>
            <td>キャプション（収録済み）</td>
            <td>A</td>
            <td>-</td>
            <td>該当コンテンツなし</td>
          </tr>
          <tr>
            <th>1.2.3</th>
            <td>音声解説又はメディアに対する代替コンテンツ（収録済み）</td>
            <td>A</td>
            <td>-</td>
            <td>該当コンテンツなし</td>
          </tr>
          <tr>
            <th>1.2.4</th>
            <td>キャプション（ライブ）</td>
            <td>AA</td>
            <td>-</td>
            <td>該当コンテンツなし</td>
          </tr>
          <tr>
            <th>1.2.5</th>
            <td>音声解説（収録済み）</td>
            <td>AA</td>
            <td>-</td>
            <td>該当コンテンツなし</td>
          </tr>
          <tr>
            <th>1.3.1</th>
            <td>情報及び関係性</td>
            <td>A</td>
            <td>○</td>
            <td>セマンティックな要素で情報・関係を表現。NVDA（PC）とVoiceOver（スマホ）で読み上げ確認済み</td>
          </tr>
          <tr>
            <th>1.3.2</th>
            <td>意味のある順序</td>
            <td>A</td>
            <td>○</td>
            <td>HTMLの順序が意味的に自然。NVDA（PC）とVoiceOver（スマホ）で読み上げ順を確認済み</td>
          </tr>
          <tr>
            <th>1.3.3</th>
            <td>感覚的な特徴</td>
            <td>A</td>
            <td>○</td>
            <td>色や位置のみに依存した説明なし</td>
          </tr>
          <tr>
            <th>1.4.1</th>
            <td>色の使用</td>
            <td>A</td>
            <td>○</td>
            <td>色に依存した情報伝達なし</td>
          </tr>
          <tr>
            <th>1.4.2</th>
            <td>音声の制御</td>
            <td>A</td>
            <td>-</td>
            <td>該当コンテンツなし</td>
          </tr>
          <tr>
            <th>1.4.3</th>
            <td>コントラスト（最低限レベル）</td>
            <td>AA</td>
            <td>○</td>
            <td>TOPページのコントラスト比（11.9:1）、下層ページのコントラスト比（11.47:1）</td>
          </tr>
          <tr>
            <th>1.4.4</th>
            <td>テキストのサイズ変更</td>
            <td>AA</td>
            <td>○</td>
            <td>PCはChromeとEdge、スマホはSafariで200%表示で情報欠落なしを確認</td>
          </tr>
          <tr>
            <th>1.4.5</th>
            <td>文字画像</td>
            <td>AA</td>
            <td>○</td>
            <td>ロゴ・背景装飾のみで、情報としての文字画像の使用なし</td>
          </tr>
          <tr>
            <th>2.1.1</th>
            <td>キーボード操作</td>
            <td>A</td>
            <td>○</td>
            <td>キーボード操作可能</td>
          </tr>
          <tr>
            <th>2.1.2</th>
            <td>キーボードトラップなし</td>
            <td>A</td>
            <td>-</td>
            <td>該当コンテンツなし</td>
          </tr>
          <tr>
            <th>2.2.1</th>
            <td>タイミング調整可能</td>
            <td>A</td>
            <td>-</td>
            <td>該当コンテンツなし</td>
          </tr>
          <tr>
            <th>2.2.2</th>
            <td>一時停止，停止及び非表示</td>
            <td>A</td>
            <td>-</td>
            <td>該当コンテンツなし</td>
          </tr>
          <tr>
            <th>2.3.1</th>
            <td>3回のせん（閃）光，又はしきい（閾）値以下</td>
            <td>A</td>
            <td>-</td>
            <td>該当コンテンツなし</td>
          </tr>
          <tr>
            <th>2.4.1</th>
            <td>ブロックスキップ</td>
            <td>A</td>
            <td>○</td>
            <td>NVDAで目的のコンテンツへの移動を確認</td>
          </tr>
          <tr>
            <th>2.4.2</th>
            <td>ページタイトル</td>
            <td>A</td>
            <td>○</td>
            <td>ページタイトルが内容を具体的に示している</td>
          </tr>
          <tr>
            <th>2.4.3</th>
            <td>フォーカス順序</td>
            <td>A</td>
            <td>○</td>
            <td>適切な順序でフォーカスされる</td>
          </tr>
          <tr>
            <th>2.4.4</th>
            <td>リンクの目的（コンテキスト内）</td>
            <td>A</td>
            <td>○</td>
            <td>リンク先が明確。適宜aria-labelで補完</td>
          </tr>
          <tr>
            <th>2.4.5</th>
            <td>複数の手段</td>
            <td>AA</td>
            <td>○</td>
            <td>TOPページから全下層ページに、下層ページから前後ページやTOPに移動可能</td>
          </tr>
          <tr>
            <th>2.4.6</th>
            <td>見出し及びラベル</td>
            <td>AA</td>
            <td>○</td>
            <td>見出しが内容を的確に示している</td>
          </tr>
          <tr>
            <th>2.4.7</th>
            <td>フォーカスの可視化</td>
            <td>AA</td>
            <td>○</td>
            <td>フォーカスインジケーターが表示</td>
          </tr>
          <tr>
            <th>3.1.1</th>
            <td>ページの言語</td>
            <td>A</td>
            <td>○</td>
            <td>HTMLのlang属性を設定</td>
          </tr>
          <tr>
            <th>3.1.2</th>
            <td>一部分の言語</td>
            <td>AA</td>
            <td>-</td>
            <td>該当コンテンツなし</td>
          </tr>
          <tr>
            <th>3.2.1</th>
            <td>フォーカス時</td>
            <td>A</td>
            <td>-</td>
            <td>該当コンテンツなし</td>
          </tr>
          <tr>
            <th>3.2.2</th>
            <td>入力時</td>
            <td>A</td>
            <td>-</td>
            <td>該当コンテンツなし</td>
          </tr>
          <tr>
            <th>3.2.3</th>
            <td>一貫したナビゲーション</td>
            <td>AA</td>
            <td>○</td>
            <td>スライド順と下層ページの前後関係が一貫</td>
          </tr>
          <tr>
            <th>3.2.4</th>
            <td>一貫した識別性</td>
            <td>AA</td>
            <td>○</td>
            <td>下層ページは共通レイアウトのため操作・要素が一貫</td>
          </tr>
          <tr>
            <th>3.3.1</th>
            <td>エラーの特定</td>
            <td>A</td>
            <td>-</td>
            <td>該当コンテンツなし</td>
          </tr>
          <tr>
            <th>3.3.2</th>
            <td>ラベル又は説明</td>
            <td>A</td>
            <td>-</td>
            <td>該当コンテンツなし</td>
          </tr>
          <tr>
            <th>3.3.3</th>
            <td>エラー修正の提案</td>
            <td>AA</td>
            <td>-</td>
            <td>該当コンテンツなし</td>
          </tr>
          <tr>
            <th>3.3.4</th>
            <td>エラー回避（法的，金融及びデータ）</td>
            <td>AA</td>
            <td>-</td>
            <td>該当コンテンツなし</td>
          </tr>
          <tr>
            <th>4.1.1</th>
            <td>構文解析</td>
            <td>A</td>
            <td>○</td>
            <td>HTML文法チェック済み（Next.jsよって生成されたタグの属性などは評価対象外）</td>
          </tr>
          <tr>
            <th>4.1.2</th>
            <td>名前（name），役割（role）及び値（value）</td>
            <td>A</td>
            <td>○</td>
            <td>カルーセルに必要なWAI-ARIA属性を設定</td>
          </tr>
        </tbody>
      </table>
    </div>
  );
};
